// <auto-generated />
using System;
using MagicVilla_Villa_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaVillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230204195447_addcontainer")]
    partial class addcontainer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("MagicVilla_Villa_API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Occupancy")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<int>("Sqft")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Something",
                            CreatedAt = new DateTime(2023, 2, 5, 1, 54, 47, 262, DateTimeKind.Local).AddTicks(3722),
                            Details = "Here should be some details",
                            ImageUrl = "",
                            Name = "Royal",
                            Occupancy = 5,
                            Rate = 1000.0,
                            Sqft = 1000,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Something",
                            CreatedAt = new DateTime(2023, 2, 5, 1, 54, 47, 262, DateTimeKind.Local).AddTicks(3735),
                            Details = "Here should be some details",
                            ImageUrl = "",
                            Name = "Polton",
                            Occupancy = 3,
                            Rate = 500.0,
                            Sqft = 2000,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Something",
                            CreatedAt = new DateTime(2023, 2, 5, 1, 54, 47, 262, DateTimeKind.Local).AddTicks(3737),
                            Details = "Here should be some details",
                            ImageUrl = "",
                            Name = "Sarantos",
                            Occupancy = 10,
                            Rate = 4000.0,
                            Sqft = 3000,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
